### ISSUE TITLE
https://solliancenet.github.io/microsoft-learning-path-build-copilots-with-cosmos-db-labs/python/instructions/07-02-generate-and-store-vectors.html - Runtime errors due to missing modules and incorrect versions

### ISSUE THREAD

**Issue by israeloros** [solliancenet/microsoft-learning-path-build-copilots-with-cosmos-db#13]
Python script fails with runtime errors due to missing modules and version mismatches.

1) The aiohttp module is missing from requirements.txt file provided in the repo.
2) If the httpx module's version is newer than 0.27.2, it might failed. The solution is to explicitly choose the right version:
pip install httpx==0.27.2

**Comment by joelhulen** [comment]
I've updated the requirements file to include these packages and others that were missing.
