### ISSUE TITLE
https://solliancenet.github.io/microsoft-learning-path-build-copilots-with-cosmos-db-labs/python/instructions/07-02-generate-and-store-vectors.html - Runtime errors due to missing data plane RBAC permissions in Cosmos DB

### ISSUE THREAD

**Issue by israeloros** [solliancenet/microsoft-learning-path-build-copilots-with-cosmos-db#14]
Issues: Users can experience runtime errors if they run the code and the principal is missing data plane RBAC permissions.

Solution:
You need to add to the document instructions to grant RBAC data plane permissions to the Entra ID principal running the code similar to this: 

az cosmosdb sql role assignment create \
   --account-name "<cosmos-account>" \
   --resource-group "<resource-group>" \
   --scope "/" \
   --principal-id "<principal-object-id>" \
   --subscription "<subscription-name>" \
   --role-definition-id "00000000-0000-0000-0000-000000000002"

**Comment by joelhulen** [comment]
Those instructions are provided here: <https://solliancenet.github.io/microsoft-learning-path-build-copilots-with-cosmos-db-labs/common/instructions/00-setup-cosmos-db.html#provide-your-user-identity-the-cosmos-db-built-in-data-contributor-rbac-role>

We link to those instructions in part 1 of lab 7 (<https://solliancenet.github.io/microsoft-learning-path-build-copilots-with-cosmos-db-labs/python/instructions/07-01-enable-azure-cosmos-db-nosql-vector-search.html#create-an-azure-cosmos-db-for-nosql-account>). We also link to the instructions within the Learn Module as setup steps to complete before doing the lab.
