### ISSUE TITLE
Setup instructions - Provide your user identity the Cosmos DB Built-in Data Contributor RBAC role

### ISSUE THREAD

**Issue by fenyan-msft** [solliancenet/microsoft-learning-path-build-copilots-with-cosmos-db#16]
For setting up the RBAC role assignment, it might be better to use the following to avoid having to get the principal:

az cosmosdb sql role assignment create \
    --account-name "XXXX" 
    --resource-group "YYYY" \
    --scope "/" \
    --principal-id $(az ad signed-in-user show --query id -o tsv) \
    --role-definition-id "00000000-0000-0000-0000-000000000002"

**Comment by joelhulen** [comment]
Great suggestion! Updated.
