### ISSUE TITLE
Enable Vector Search for Azure Cosmos DB for NoSQL lab - container provisioning failure

### ISSUE THREAD

**Issue by fenyan-msft** [solliancenet/microsoft-learning-path-build-copilots-with-cosmos-db#17]
Although I've enabled vector search and checked under Features it is on, I get this error when provisioning the container: 
Message: {"code":"BadRequest","message":"Message: {\"Errors\":[\"A Container Vector Policy has been provided, but the capability has not been enabled on your account. 

Container provisioning worked after I waited about 15 minutes. I have seen this happening before so it would be good to add a sentence to say that it may be necessary to wait for awhile.

**Comment by joelhulen** [comment]
I've added the note per your suggestion. Thanks!
