### ISSUE TITLE
Python SDK labs	07 - Generate vector embeddings with Azure OpenAI and store them in Azure Cosmos DB for NoSQL - indentation

### ISSUE THREAD

**Issue by fenyan-msft** [solliancenet/microsoft-learning-path-build-copilots-with-cosmos-db#18]
When I copy and paste the code blocks, I'm getting an addition space in front of each line that needs to be removed. If the space can't be taken out on the page, then perhaps add something to say that it needs to be removed

**Comment by joelhulen** [comment]
I've fixed this across all the Python labs.
