### ISSUE TITLE
Module 1 Section 4 Connection Options

### ISSUE THREAD

**Issue by howardginsburg** [solliancenet/microsoft-learning-path-build-copilots-with-cosmos-db#20]
The module highlights the more common approach of connecting using connection strings and keys, and highlights that you can use identities, but leaves it at that.  Consider adding a bit more content on the importance of it, or adding a link to https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/security/

**Comment by joelhulen** [comment]
Updated to also include Entra ID authentication examples.
