### ISSUE TITLE
GitHub.io Lab Numbers

### ISSUE THREAD

**Issue by howardginsburg** [solliancenet/microsoft-learning-path-build-copilots-with-cosmos-db#22]
The numbering of the labs on github.io for copilots needs to be fixed.

![image](https://github.com/user-attachments/assets/171ac6b5-7e86-4790-8f81-1cfed6d35fe2)

**Comment by joelhulen** [comment]
Those are in the correct order. There are just 4 labs for module 7. @kylebunting , perhaps you can name these 7.1, 7.2, 7.3, and 7.4?

**Comment by joelhulen** [comment]
Renamed the modules as discussed.
