### ISSUE TITLE
LP01M01 - use-azure-cosmos-db-sql-api-sdk/includes/8-summary.md links not working

### ISSUE THREAD

**Issue by fenyan-msft** [solliancenet/microsoft-learning-path-build-copilots-with-cosmos-db#4]
The first two .NET SDK and first Python and JavaScript links are not working

**Comment by joelhulen** [comment]
These are relative links that will work once the learning modules are published to both the sandbox and release environments.

**Comment by fenyan-msft** [comment]
Thank you, Joel
