### ISSUE TITLE
LP03M07 - build-copilots-with-azure-cosmos-db-nosql/includes/3-exercise-enable-azure-cosmos-db-nosql-vector-search.md should not have bullet point hyperlinks

### ISSUE THREAD

**Issue by israeloros** [solliancenet/microsoft-learning-path-build-copilots-with-cosmos-db#9]
The bullet points should not be hyperlinks unless they will take you to a specific document or page. Perhaps they can be **bold** or change the font color to highlight them. It is confusing that the links are broken.

**Comment by joelhulen** [comment]
All of the links have been fixed.
